COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\gentle_alarms\bortolazzi_notturno_short.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\guitar\spanish_guitar_short.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\alarms_gradual_original_length\bortolazzi_notturno.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\guitar\spanish_guitar.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\alarms\aguado_guitar_lessons_no2.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\guitar\8_lessons_for_the_guitar.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\gentle_alarms\aguado_guitar_etude_no27.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\guitar\guitar_etudes.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\gentle_alarms\knoop_waltz_no1_short.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\guitar\six_waltzes_short.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\alarms_gradual_original_length\knoop_waltz_no1.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\guitar\six_waltzes.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\gentle_alarms\carcassi_caprice_short.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\guitar\caprice_short.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\alarms_gradual_original_length\carcassi_caprice.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\guitar\caprice.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\Rocky Soundtrack - Gonna Fly Now (Theme Song).wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\modern instramental\rocky_gonna_fly_now.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\01 Ghost In A Shell.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\modern instramental\ghost_in_the_shell.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\25 Super Mario Galaxy.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\modern instramental\super_mario_galaxy.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\wake\bach_gounod_ave_maria.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\piano\ave_maria.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\gentle_alarms\dvorak_american_quartet_short.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\orchestral\american_quartet_short.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\alarms_gradual_original_length\dvorak_american_quartet.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\orchestral\american_quartet.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\gentle_alarms\grieg_peer_gynt_morning_short.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\orchestral\morning_mood_short.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\alarms_gradual_original_length\grieg_peer_gynt_morning.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\orchestral\morning_mood.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\alarms_loud_original_length\rossini_william_tell.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\orchestral\william_tell.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\alarms\rossini_william_tell_short.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\orchestral\william_tell_short.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\gentle_alarms\offenbach_can_can_short.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\orchestral\can_can_short.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\alarms_gradual_original_length\offenbach_can_can.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\orchestral\can_can.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\13 Concerto for 2 Harpsichords in C.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\orchestral\bach_2_harpsichords.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\gentle_alarms\fucik_entry_of_gladiators_short.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\orchestral\entry_of_gladiators_short.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\alarms_gradual_original_length\fucik_entry_of_gladiators.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\orchestral\entry_of_gladiators.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\alarms_loud_original_length\beethoven_symphony_5.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\orchestral\symphony_no_5.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\alarms\beethoven_symphony_5_short.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\orchestral\symphony_no_5_short.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\alarms\beethoven_symphony_5_very_short.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\orchestral\symphony_no_5_very_short.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\gentle_alarms\paganini_caprice_no24_short.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\orchestral\caprice_24_short.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\alarms_gradual_original_length\paganini_caprice_no24.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\orchestral\caprice_24.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\11 Menuetto.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\orchestral\menuetto.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\alarms_loud_original_length\mozart_rondo_alla_turca.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\orchestral\rondo_alla_turca.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\alarms\mozart_rondo_alla_turca_short.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\orchestral\rondo_alla_turca_short.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\alarms\mozart_rondo_alla_turca_very_short.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\orchestral\rondo_alla_turca_very_short.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\alarms\czerny_etude_op849_no4.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\piano\op_849_etude_4.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\gentle_alarms\burgmuller_la_candeur.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\piano\la_candeur.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\gentle_alarms\beethoven_fur_elise_short.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\piano\fur_elise_short.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\gentle_alarms\beethoven_fur_elise_very_short.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\piano\fur_elise_very_short.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\alarms_gradual_original_length\beethoven_fur_elise.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\piano\fur_elise.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\alarms_gradual_original_length\rachmaninoff_prelude_op32.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\piano\prelude.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\alarms\myra_wake_up.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\recordings\myra_wake_up.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\gentle_alarms\myra_wake_up_little_one.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\recordings\myra_wake_up_little_one.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\wake\birds.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\sounds\birds.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\wake\birds_ambiance.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\sounds\birds_ambiance.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\wake\calming_rain.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\sounds\calming_rain.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\wake\cicadas_at_night.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\sounds\cicadas_at_night.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\wake\forest_birds.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\sounds\forest_birds.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\wake\frogs_croaking.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\sounds\frogs_croaking.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\wake\gentle_rain.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\sounds\gentle_rain.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\wake\morning_birds.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\sounds\morning_birds.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\wake\ocean_waves.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\sounds\ocean_waves.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\wake\rain_and_wind_chimes.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\sounds\rain_and_wind_chimes.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\wake\summer_evening.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\sounds\summer_evening.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\wake\wind_chimes.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\sounds\wind_chimes.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\Bob Marley - Three Little Birds.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\three_little_birds.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\Old time rock and roll.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\track 7.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\Buddy Holly Peggy Sue.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\peggy_sue.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\09 Moonshadow.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\moonshadow.wav"

COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\07 Morning Has Broken.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\morning_has_broken.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\Morning Has Broken.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\morning_has_broken.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\01 Hotel California.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\hotel_california.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\01 I love A Rainy Night.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\i_love_a_rainy_night.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\ub40 - can't help falling in love.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\cant_help_falling_in_love.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\11 Underground.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\underground.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\02 Sleep Through The Static 1.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\sleep_through_the_static.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\05 Time in a Bottle.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\time_in_a_bottle.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\04 Which Way Are You Goin'.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\which_way_are_you_goin.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\Jimmy Buffet - Volcano.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\volcano.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\Jimmy Buffett - Cheeseburger In Paradise.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\cheeseburger_in_paradise.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\01 Carry On Wayward Son.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\carry_on_wayward_son.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\04 Dust In The Wind.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\dust_in_the_wind.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\alarms\bella_ciao.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\bella_ciao.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\07 Going to California.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\going_to_california.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\04 Stairway to Heaven.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\stairway_to_heaven.wav"

COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\05 Lightning Crashes.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\lightning_crashes.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\06 Free Bird.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\free_bird.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\02 ...And Justice For All.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\and_justice_for_all.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\03 For Whom The Bell Tolls.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\for_whom_the_bell_tolls.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\09 Of Wolf And Man.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\of_wolf_and_man.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\04 One.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\one.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\04 The Unforgiven.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\the_unforgiven.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\Monkees - Daydream Believer.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\daydream_believer.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\Nena - 99 Red Balloons.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\99_red_balloons.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\03 Down In It.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\down_in_it.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\03 Heart-Shaped Box.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\heart_shaped_box.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\05 Lithium.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\lithium.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\01 Smells Like Teen Spirit.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\smells_like_teen_spirit.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\01 Sunrise.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\sunrise.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\10 Morning Glory.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\morning_glory.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\02 Crazy Train.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\crazy_train.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\04 Dee [Instrumental].wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\dee_instrumental.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\01 Shining In The Light.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\shining_in_the_light.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\angel of the morning - pretenders.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\angel_of_the_morning.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\alarms_loud_original_length\never_gonna_give_you_up.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\never_gonna_give_you_up.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\alarms\rick_rolled_short.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\rick_rolled_short.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\05 Man of Constant Sorrow.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\man_of_constant_sorrow.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\magic carpet ride.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\magic_carpet_ride.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\Styx - Come Sail Away.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\come_sail_away.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\Styx - Mr Roboto.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\mr_roboto.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\80's -Survivor - Eye of the Tiger (from ROCKY).wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\eye_of_the_tiger.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\Tenacious D - Tribute.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\tribute.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\500 miles.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\miles.wav"
COPY "D:\Tim\Personal\Projects\Tim Alarm Clock\warren zevon - Warewolf in London.wav" "D:\Tim\Personal\Projects\Tim Alarm Clock\songs\werewolves_of_london.wav"
